### ISSUE TITLE
Demo wearables problem

### ISSUE THREAD

**Issue by CDTH06** [nosoop/SM-TFCustAttr#10]
Before I install Custom Attributes, custom wearables (boots and shields) on Demo works fine(I use CW3). But when I install it, wearables are broken. About broken I mean, when I equip shield Demo just drop his body (like when you die) he still alive, but he can't move. Can please someone help me?

**Comment by nosoop** [comment]
I can't think of anything specific to the core of Custom Attributes that would cause that &mdash; what other files have you touched in the process?  If you have the Starter Pack installed, try removing that, then the core plugin if the issue remains.

**Comment by CDTH06** [comment]
I remove starter pack, then remove core plugins. Demo still stucks
May be it's problem of one is requirment plugins for CA
